# Generated by Django 3.0.4 on 2020-07-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_costlimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costlimit',
            name='reached_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
